version: '3'
services:
  web:
    depends_on:
      - mongodb
    image: mapdraw
    container_name: mapdraw-web
    ports:
      - "3000:3000"
    environment:
      - DOCKER=true
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
    volumes:
      - jwt_secret_volume:/run/secrets
  mongodb:
    image: mongo
    container_name: mapdraw-mongodb
    volumes:
      - mapdraw-mongodb-data:/data/db

volumes:
  mapdraw-mongodb-data:
  jwt_secret_volume: