version: '3'
services:
  web:
    depends_on:
      - mongodb
    image: giomap
    container_name: giomap-web
    ports:
      - "3000:3000"
    environment:
      - DOCKER=true
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
    volumes:
      - jwt_secret_volume:/run/secrets
    restart: always
  mongodb:
    image: mongo
    container_name: giomap-mongodb
    restart: always
    volumes:
      - giomap-mongodb-data:/data/db

volumes:
  giomap-mongodb-data:
  jwt_secret_volume: